mutation {
    deleteSavedSearch(id: "%s") {
        id,
        auxUserId,
        name,
        retailCountry,
        searchUri,
        query,
        isEnabled,
        resultCount,
        frequency,
        type,
        createdOn,
        lastModified
    }
}