# should be developer-machine agnostic, except dev-mongo volume

version: "3"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.4.0"
    container_name: "dev-elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    networks:
      - elk

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.4.0"
    container_name: "dev-kibana"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  cerebro:
    image: yannart/cerebro:latest
    ports:
      - "9000:9000"
    networks:
      - elk

networks:
  elk:
    driver: bridge
